name: on-pullrequest-phpcs
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpcs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: download phpcs
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - name: download cs2pr
        run: curl -OL https://raw.githubusercontent.com/staabm/annotate-pull-request-from-checkstyle/master/cs2pr
      - name: exec phpcs
        continue-on-error: true
        run: php phpcs.phar --standard=PSR12 --report=checkstyle -q . | php cs2pr
