name: php-static-cheker
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  php-static-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: download phpcs
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - name: download phpmc  
        run: curl -OL https://phpmd.org/static/latest/phpmd.phar
      - name: dwonload phpstan
        run: curl -OL https://github.com/phpstan/phpstan/releases/download/1.7.15/phpstan.phar
      - name: exec ls
        run: ls -lR
      - name: exec phpcs
        continue-on-error: true
        uses: chekalsky/phpcs-action@v1
          with:
            phpcs_bin_path: 'php phpcs.phar'
      - name: exec phpmd
        continue-on-error: true
        run: php phpmd.phar .  github cleancode,codesize,controversial,design,naming,unusedcode
      - name: exec phpstan
        continue-on-error: true
        run: php phpstan.phar analyse --level=9 --error-format=github .

