name: on-pullrequest-phpstan
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  phpstan-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: dwonload phpstan
        run: curl -OL https://github.com/phpstan/phpstan/releases/download/1.7.15/phpstan.phar
      - name: exec phpstan
        continue-on-error: true
        run: php phpstan.phar analyse --level=9 --error-format=github .

